<?php

namespace JA\GameBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GameSheetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameSheetRepository extends EntityRepository
{
}
